import fs from "node:fs/promises";
import path from "node:path";

const MAGIC = 0x50525a42, HEADER = 24;
const TYPE = { SESSION_BEGIN: 1, DICTIONARY_UPDATE: 2, MATCH_DELTA: 3, PLAYER_DELTA: 0x11, PLAYER_REMOVE: 0x12, PLAYER_STATS: 0x13, PLAYER_NETWORK: 0x14, ZONE: 0x20, MAIN_ZONE: 0x21, FOB: 0x30, FOB_DELTA: 0x31, FOB_REMOVE: 0x32, VEHICLE: 0x40, VEHICLE_REMOVE: 0x41 };
const F = { POS: 1, YAW: 2, HEALTH: 4, PRESENCE: 8, TEAM: 16, SQUAD: 32, FIRETEAM: 64, ROLE: 128, VEHICLE: 256, LEADER: 512 };
const STAT_NAMES = ["kills", "wounds", "deaths", "teamKills", "vehicleKills", "revives", "healPoints", "combatScore", "objectiveScore", "teamworkScore"];

export class ReplayDecoder {
  constructor(scanner) { this.scanner = scanner; this.cache = new Map(); }
  async read(id, atMs = 0) {
    const session = await this.scanner.get(id); if (!session) return null;
    const directory = await this.scanner.resolve(id); const target = Math.max(0, Number(atMs) || 0);
    const state = createState(session); let resolvedAtMs = 0, invalidRecords = 0;
    const names = (await fs.readdir(path.join(directory, "segments"), { withFileTypes: true }).catch(() => [])).filter((x) => x.isFile() && /^\d{6}\.(?:open\.)?rps$/.test(x.name)).map((x) => x.name).sort();
    for (const name of names) {
      const bytes = await this.readSegment(directory, name);
      for (let offset = 0; offset + HEADER <= bytes.length;) {
        const payloadLength = bytes.readUInt32LE(offset + 16), end = offset + HEADER + payloadLength, elapsed = bytes.readUInt32LE(offset + 12);
        if (bytes.readUInt32LE(offset) !== MAGIC || bytes.readUInt8(offset + 4) !== 1 || end > bytes.length) { invalidRecords++; break; }
        if (elapsed > target) return result(session, target, resolvedAtMs, state, names.length, invalidRecords);
        const payload = bytes.subarray(offset + HEADER, end);
        if (crc32(payload) === bytes.readUInt32LE(offset + 20)) { try { apply(state, bytes.readUInt8(offset + 5), decode(payload)); resolvedAtMs = elapsed; } catch { invalidRecords++; } } else invalidRecords++;
        offset = end;
      }
    }
    return result(session, target, resolvedAtMs, state, names.length, invalidRecords);
  }
  async readSegment(directory, name) { const key = `${directory}:${name}`; const value = this.cache.get(key); if (value) return value; const bytes = await fs.readFile(path.join(directory, "segments", name)); this.cache.set(key, bytes); while (this.cache.size > 3) this.cache.delete(this.cache.keys().next().value); return bytes; }
}

function createState(session) { return { server: {}, teams: [], dictionary: new Map(), players: new Map(), stats: new Map(), pings: new Map(), zones: new Map(), mainZones: new Map(), fobs: new Map(), vehicles: new Map(), session }; }
function apply(s, type, p) { switch (type) { case TYPE.SESSION_BEGIN: s.server = { ...s.server, map: p?.map || "", layer: p?.layer || "", mode: p?.mode || "" }; break; case TYPE.MATCH_DELTA: s.server = { ...s.server, ...(p?.server || {}) }; s.teams = Array.isArray(p?.teams) ? p.teams : s.teams; break; case TYPE.DICTIONARY_UPDATE: for (const x of p?.players || []) if (Array.isArray(x)) s.dictionary.set(String(x[0]), x[1] || {}); break; case TYPE.PLAYER_DELTA: for (const x of p?.changes || []) player(s, x); break; case TYPE.PLAYER_REMOVE: for (const id of p?.ids || []) { s.players.delete(String(id)); s.stats.delete(String(id)); s.pings.delete(String(id)); } break; case TYPE.PLAYER_STATS: for (const x of p?.changes || []) if (Array.isArray(x)) s.stats.set(String(x[0]), x[1]); break; case TYPE.PLAYER_NETWORK: for (const x of p?.players || []) if (Array.isArray(x)) s.pings.set(String(x[0]), x[1]); break; case TYPE.ZONE: upsert(s.zones, p?.upsert); break; case TYPE.MAIN_ZONE: upsert(s.mainZones, p?.upsert); break; case TYPE.FOB: case TYPE.FOB_DELTA: upsert(s.fobs, p?.fobs); break; case TYPE.VEHICLE: upsert(s.vehicles, p?.upsert); break; case TYPE.FOB_REMOVE: remove(s.fobs, p?.ids); break; case TYPE.VEHICLE_REMOVE: remove(s.vehicles, p?.ids); break; } }
function player(s, x) { if (!Array.isArray(x)) return; const id = String(x[0]), p = s.players.get(id) || { position: null, yaw: null, health: null, presence: "", team: null, squad: null, fireTeam: null, role: "", vehicle: "", leader: false }; let i = 2, m = Number(x[1]) || 0; if (m & F.POS) p.position = x[i++]; if (m & F.YAW) p.yaw = x[i++]; if (m & F.HEALTH) p.health = x[i++]; if (m & F.PRESENCE) p.presence = text(x[i++]); if (m & F.TEAM) p.team = number(x[i++]); if (m & F.SQUAD) p.squad = number(x[i++]); if (m & F.FIRETEAM) p.fireTeam = number(x[i++]); if (m & F.ROLE) p.role = text(x[i++]); if (m & F.VEHICLE) p.vehicle = text(x[i++]); if (m & F.LEADER) p.leader = Boolean(x[i++]); s.players.set(id, p); }
function upsert(map, xs) { for (const x of xs || []) if (Array.isArray(x)) map.set(String(x[0]), x[1] || {}); } function remove(map, ids) { for (const id of ids || []) map.delete(String(id)); }
function result(session, atMs, resolvedAtMs, s, segments, invalidRecords) { const players = [...s.players.entries()].map(([id, p]) => { const d = s.dictionary.get(id) || {}, pos = Array.isArray(p.position) ? { x: number(p.position[0]), y: number(p.position[1]), z: number(p.position[2] ?? 0) } : null, stats = s.stats.get(id) || []; return { identity: { key: text(d.key || id), name: nameOf(id, d), steamID: text(d.steamID) }, match: { teamId: p.team, squadId: p.squad, fireTeamIndex: p.fireTeam, isLeader: p.leader, role: p.role }, telemetry: { position: pos, yaw: number(p.yaw), health: number(p.health), hasPosition: Boolean(pos) }, presence: { state: p.presence }, vehicle: { vehicleType: p.vehicle }, network: { gamePing: number(s.pings.get(id)) }, combat: Object.fromEntries(STAT_NAMES.map((n, i) => [n, number(stats[i])])) }; }).sort((a,b) => a.identity.name.localeCompare(b.identity.name)); return { session, atMs, resolvedAtMs, state: { meta: { replay: true, replayAtMs: atMs }, server: s.server, teams: s.teams, players, assets: { captureZones: assets(s.zones), mainZones: assets(s.mainZones), fobs: assets(s.fobs), vehicles: assets(s.vehicles) } }, diagnostics: { segments, invalidRecords } }; }
function assets(map) { return [...map.entries()].map(([id, x]) => ({ ...(x && typeof x === "object" ? x : {}), id })); } function nameOf(id, d) { const n = text(d.name || d.displayName || d.playerName || d.steamName || d.steamID); return n && !/^unknown/i.test(n) ? n : `Player ${id}`; } function text(x) { return String(x ?? "").trim(); } function number(x) { const n = Number(x); return Number.isFinite(n) ? n : null; }
function crc32(b) { let c = 0xffffffff; for (const v of b) { c ^= v; for (let i = 0; i < 8; i++) c = (c >>> 1) ^ (0xedb88320 & -(c & 1)); } return (c ^ 0xffffffff) >>> 0; }
function decode(b) { const c = { o: 0 }; const v = value(b,c); if (c.o !== b.length) throw Error("MessagePack trailing data"); return v; } function value(b,c) { if(c.o>=b.length) throw Error("MessagePack EOF"); const h=b[c.o++]; if(h<=0x7f)return h;if(h>=0xe0)return h-256;if((h&0xe0)===0xa0)return str(b,c,h&31);if((h&0xf0)===0x90)return arr(b,c,h&15);if((h&0xf0)===0x80)return obj(b,c,h&15);if(h===0xc0)return null;if(h===0xc2)return false;if(h===0xc3)return true;if(h===0xcc)return b[c.o++];if(h===0xcd){let x=b.readUInt16BE(c.o);c.o+=2;return x}if(h===0xce){let x=b.readUInt32BE(c.o);c.o+=4;return x}if(h===0xd0){let x=b.readInt8(c.o);c.o++;return x}if(h===0xd1){let x=b.readInt16BE(c.o);c.o+=2;return x}if(h===0xd2){let x=b.readInt32BE(c.o);c.o+=4;return x}if(h===0xca){let x=b.readFloatBE(c.o);c.o+=4;return x}if(h===0xcb){let x=b.readDoubleBE(c.o);c.o+=8;return x}if(h===0xd9){let n=b[c.o++];return str(b,c,n)}if(h===0xda){let n=b.readUInt16BE(c.o);c.o+=2;return str(b,c,n)}if(h===0xdb){let n=b.readUInt32BE(c.o);c.o+=4;return str(b,c,n)}if(h===0xdc){let n=b.readUInt16BE(c.o);c.o+=2;return arr(b,c,n)}if(h===0xdd){let n=b.readUInt32BE(c.o);c.o+=4;return arr(b,c,n)}if(h===0xde){let n=b.readUInt16BE(c.o);c.o+=2;return obj(b,c,n)}if(h===0xdf){let n=b.readUInt32BE(c.o);c.o+=4;return obj(b,c,n)}throw Error(`Unsupported MessagePack 0x${h.toString(16)}`) } function str(b,c,n){if(c.o+n>b.length)throw Error("MessagePack EOF");let s=b.subarray(c.o,c.o+n).toString("utf8");c.o+=n;return s} function arr(b,c,n){let a=[];while(n--)a.push(value(b,c));return a} function obj(b,c,n){let o={};while(n--)o[String(value(b,c))]=value(b,c);return o}
