export const pluginCatalog = [
  {
    id: "squad-order-tracker",
    name: "建队顺序追踪",
    description: "根据 Squad 日志记录小队创建时间，并在网页中显示建队顺序。",
    category: "Squad",
    icon: "",
    enabled: true,
    subscribed: true,
    version: "1.0.0",
    author: "BZSS",
    status: "ok",
    configSchema: [
      {
        key: "enableTeamSplit",
        label: "按 Team 分组",
        type: "boolean",
        defaultValue: true,
        description: "开启后会分别显示 Team 1 和 Team 2 的建队顺序。",
      },
      {
        key: "refreshIntervalMs",
        label: "刷新间隔",
        type: "number",
        defaultValue: 1000,
        description: "单位：毫秒。用于控制前端或内部状态刷新频率。",
      },
      {
        key: "displayMode",
        label: "显示模式",
        type: "select",
        defaultValue: "compact",
        options: [
          { label: "紧凑模式", value: "compact" },
          { label: "详细模式", value: "detailed" },
        ],
      },
    ],
    config: {
      enableTeamSplit: true,
      refreshIntervalMs: 1000,
      displayMode: "compact",
    },
  },
  {
    id: "raw-log-console",
    name: "原生日志控制台",
    description: "接收、缓存、过滤并显示 Squad 原生日志。",
    category: "Logs",
    icon: "",
    enabled: true,
    subscribed: true,
    version: "1.0.0",
    author: "BZSS",
    status: "ok",
    configSchema: [
      {
        key: "maxBufferedLines",
        label: "最大缓存行数",
        type: "number",
        defaultValue: 3000,
      },
      {
        key: "blacklistRegex",
        label: "过滤正则",
        type: "textarea",
        defaultValue: "",
        description: "匹配到的日志会被隐藏或丢弃。",
      },
    ],
    config: {
      maxBufferedLines: 3000,
      blacklistRegex: "",
    },
  },
  {
    id: "udp-event-forwarder",
    name: "UDP 事件转发",
    description: "将内部事件收集器中的事件通过 UDP 转发给外部服务。",
    category: "Events",
    icon: "",
    enabled: false,
    subscribed: true,
    version: "0.1.0",
    author: "BZSS",
    status: "disabled",
    configSchema: [
      {
        key: "host",
        label: "目标 Host",
        type: "string",
        required: true,
        defaultValue: "127.0.0.1",
      },
      {
        key: "port",
        label: "目标端口",
        type: "number",
        required: true,
        defaultValue: 9999,
      },
      {
        key: "includeRawLog",
        label: "包含原始日志",
        type: "boolean",
        defaultValue: true,
      },
    ],
    config: {
      host: "127.0.0.1",
      port: 9999,
      includeRawLog: true,
    },
  },
];
