// -*- coding: utf-8 -*-

export const squadNameRules = Object.freeze({
  version: 1,
  defaultSquadNamePatterns: Object.freeze([
    "^squad\\s*\\d+$",
    "^小队\\s*\\d+$",
    "^队伍\\s*\\d+$",
    "^team\\s*\\d+$",
  ]),
  priority: Object.freeze([
    "logistics",
    "support",
    "vehicle",
    "infantry",
  ]),
  infantry: Object.freeze({
    exactWhitelist: Object.freeze([
      "inf",
      "infantry",
      "ied",
      "步兵",
      "步兵队",
      "command squad",
    ]),
    contains: Object.freeze([
      "步兵",
      "infantry",
      "inf",
      "空突",
      "air assault",
      "airassault",
      "newbie",
      "萌新",
      "主力",
      "进攻",
      "防守",
    ]),
    blacklist: Object.freeze([
      "步兵战车",
      "ifv",
      "apc",
      "btr",
      "bmp",
      "lav",
      "mrap",
      "tank",
      "mbt",
      "坦克",
      "装甲",
      "载具",
      "步战",
      "轮战",
      "迫击炮",
      "mortar",
      "后勤",
      "logi",
      "fob",
      "hab",
      "运输",
    ]),
    regex: Object.freeze([]),
  }),
  vehicle: Object.freeze({
    exactWhitelist: Object.freeze([
      "tank",
      "mbt",
      "ifv",
      "apc",
      "btr",
      "bmp",
      "lav",
      "mrap",
      "matv",
      "spg",
      "spg 1",
      "armor",
      "armour",
      "vic",
      "vehicle",
      "82a",
      "zlt05",
      "fv107",
      "08ifv",
      "92ifv",
      "pjp车",
      "步兵战车",
      "坦克",
      "装甲",
      "载具",
      "步战",
      "轮战",
    ]),
    aliases: Object.freeze({
      exactWhitelist: Object.freeze([
        "zcc",
        "bjc",
        "zjc",
        "m-atv",
        "m atv",
      ]),
    }),
    contains: Object.freeze([
      "坦克",
      "装甲",
      "载具",
      "步战",
      "轮战",
      "ifv",
      "apc",
      "btr",
      "bmp",
      "lav",
      "mrap",
      "tank",
      "mbt",
      "armor",
      "armour",
      "vehicle",
      "vic",
      "stryker",
      "brdm",
      "zbd",
      "ztz",
      "spg",
      "spg 1",
      "步兵战车",
      "t72",
      "t-72",
      "m1a2",
      "challenger",
      "leopard",
      "豹2",
      "99a",
      "炮车",
      "车队",
    ]),
    blacklist: Object.freeze([
      "无载具",
      "no vehicle",
      "no armor",
      "no armour",
      "禁载具",
    ]),
    regex: Object.freeze([
      "^\\d{2}\\s*-?\\s*\\d{2}$",
      "^m1[0-9a-z-]*$",
      "^fv[0-9a-z-]*$",
    ]),
    classes: Object.freeze({
      ifv: Object.freeze({
        label: "步兵战车",
        exactWhitelist: Object.freeze([
          "ifv",
          "bmp",
          "bmp2",
          "bmp-2",
          "bmp 2",
          "步兵战车",
          "步战",
          "步战车",
          "bjc",
        ]),
        aliases: Object.freeze({
          exactWhitelist: Object.freeze([
            "zcc",
            "bjc",
          ]),
        }),
        contains: Object.freeze([
          "ifv",
          "bmp",
          "bmp2",
          "bmp-2",
          "步兵战车",
          "步战",
          "步战车",
        ]),
        regex: Object.freeze([]),
      }),
      light_vehicle: Object.freeze({
        label: "轻型载具",
        exactWhitelist: Object.freeze([
          "matv",
          "m-atv",
          "m atv",
          "轻型载具",
        ]),
        aliases: Object.freeze({
          exactWhitelist: Object.freeze([
            "matv",
            "m-atv",
            "m atv",
          ]),
        }),
        contains: Object.freeze([
          "matv",
          "m-atv",
          "m atv",
          "轻型载具",
        ]),
        regex: Object.freeze([]),
      }),
      tank: Object.freeze({
        label: "坦克",
        exactWhitelist: Object.freeze([
          "99a",
          "99a2",
          "ztz99a",
          "ztz 99a",
          "坦克",
          "mbt",
        ]),
        aliases: Object.freeze({
          exactWhitelist: Object.freeze([
            "99a",
            "99a2",
          ]),
        }),
        contains: Object.freeze([
          "99a",
          "99a2",
          "ztz99a",
          "ztz 99a",
          "坦克",
          "mbt",
        ]),
        regex: Object.freeze([]),
      }),
      spg: Object.freeze({
        label: "SPG",
        exactWhitelist: Object.freeze([
          "spg",
          "spg1",
          "spg 1",
          "炮车",
          "火炮车",
          "自行火炮",
        ]),
        aliases: Object.freeze({
          exactWhitelist: Object.freeze([
            "spg",
          ]),
        }),
        contains: Object.freeze([
          "spg",
          "炮车",
          "火炮车",
          "自行火炮",
        ]),
        regex: Object.freeze([]),
      }),
    }),
  }),
  support: Object.freeze({
    exactWhitelist: Object.freeze([
      "mortar",
      "logi",
      "fob",
      "hab",
      "迫击炮",
      "后勤",
      "补给",
      "支援",
    ]),
    aliases: Object.freeze({
      exactWhitelist: Object.freeze([
        "zsj",
      ]),
    }),
    contains: Object.freeze([
      "迫击炮",
      "mortar",
      "后勤",
      "logi",
      "补给",
      "运输",
      "火力支援",
      "支援",
      "fob",
      "hab",
      "工兵",
      "engineer",
      "侦察",
      "recon",
      "直升机",
      "heli",
      "运输直升机",
    ]),
    blacklist: Object.freeze([]),
    regex: Object.freeze([]),
  }),
  logistics: Object.freeze({
    exactWhitelist: Object.freeze([
      "后勤",
      "logi",
      "logistics",
      "fob",
      "hab",
      "transport",
      "运输",
      "补给",
    ]),
    aliases: Object.freeze({
      exactWhitelist: Object.freeze([
        "logi team",
      ]),
    }),
    contains: Object.freeze([
      "后勤",
      "logi",
      "logistics",
      "fob",
      "hab",
      "transport",
      "运输",
      "补给",
    ]),
    blacklist: Object.freeze([]),
    regex: Object.freeze([]),
  }),
});

export default squadNameRules;
