// -*- coding: utf-8 -*-

export const squadNameRules = Object.freeze({
  version: 1,
  defaultSquadNamePatterns: Object.freeze([
    "^squad\\s*\\d+$",
    "^小队\\s*\\d+$",
    "^队伍\\s*\\d+$",
    "^team\\s*\\d+$",
  ]),
  priority: Object.freeze([
    "support",
    "vehicle",
    "infantry",
  ]),
  infantry: Object.freeze({
    exactWhitelist: Object.freeze([
      "inf",
      "infantry",
      "步兵",
      "步兵队",
    ]),
    contains: Object.freeze([
      "步兵",
      "infantry",
      "inf",
      "空突",
      "air assault",
      "airassault",
      "newbie",
      "萌新",
      "主力",
      "进攻",
      "防守",
    ]),
    blacklist: Object.freeze([
      "步兵战车",
      "ifv",
      "apc",
      "btr",
      "bmp",
      "lav",
      "mrap",
      "tank",
      "mbt",
      "坦克",
      "装甲",
      "载具",
      "步战",
      "轮战",
      "迫击炮",
      "mortar",
      "后勤",
      "logi",
      "fob",
      "hab",
      "运输",
    ]),
    regex: Object.freeze([]),
  }),
  vehicle: Object.freeze({
    exactWhitelist: Object.freeze([
      "tank",
      "mbt",
      "ifv",
      "apc",
      "btr",
      "bmp",
      "lav",
      "mrap",
      "armor",
      "armour",
      "vic",
      "vehicle",
      "步兵战车",
      "坦克",
      "装甲",
      "载具",
      "步战",
      "轮战",
    ]),
    contains: Object.freeze([
      "坦克",
      "装甲",
      "载具",
      "步战",
      "轮战",
      "ifv",
      "apc",
      "btr",
      "bmp",
      "lav",
      "mrap",
      "tank",
      "mbt",
      "armor",
      "armour",
      "vehicle",
      "vic",
      "stryker",
      "brdm",
      "zbd",
      "ztz",
      "步兵战车",
      "t72",
      "t-72",
      "m1a2",
      "challenger",
      "leopard",
      "豹2",
      "99a",
      "炮车",
      "车队",
    ]),
    blacklist: Object.freeze([
      "无载具",
      "no vehicle",
      "no armor",
      "no armour",
      "禁载具",
    ]),
    regex: Object.freeze([]),
  }),
  support: Object.freeze({
    exactWhitelist: Object.freeze([
      "mortar",
      "logi",
      "fob",
      "hab",
      "迫击炮",
      "后勤",
      "补给",
      "支援",
    ]),
    contains: Object.freeze([
      "迫击炮",
      "mortar",
      "后勤",
      "logi",
      "补给",
      "运输",
      "火力支援",
      "支援",
      "fob",
      "hab",
      "工兵",
      "engineer",
      "侦察",
      "recon",
      "直升机",
      "heli",
      "运输直升机",
    ]),
    blacklist: Object.freeze([]),
    regex: Object.freeze([]),
  }),
});

export default squadNameRules;
