// -*- coding: utf-8 -*-
import fs from "node:fs/promises";
import path from "node:path";

export const CONFIG_NAMESPACE_OWNERSHIP = Object.freeze({
  core:"core.json",server:"core.json",console:"core.json",fileIO:"core.json",task:"core.json",runtimeState:"core.json",eventPipeline:"core.json",performance:"core.json",warmup:"core.json",logClock:"core.json",squadNameClassifier:"core.json",
  web:"web.json",playerIdentityDisplay:"web.json",serverTickRate:"web.json",webModules:"web.json",auth:"auth.json",rcon:"rcon.json",udp:"logpost.json",pythonLogParser:"logpost.json",logPostFileBridge:"logpost.json",steam:"steam.json",steamPlaytimeDatabase:"steam.json",ipLookup:"steam.json",modules:"modules.json",plugins:"plugins.json",reserveSystem:"services.json",reserveExchange:"services.json",database:"services.json",bzssCore:"services.json",integrations:"integrations.json",settingsEditor:"settings.json",
});
const SECRETS=Object.freeze({"rcon.password":"BZSS_RCON_PASSWORD","steam.apiKey":"BZSS_STEAM_API_KEY","ipLookup.ipinfoToken":"BZSS_IPINFO_TOKEN","modules.astrbotBridge.apiToken":"BZSS_ASTRBOT_TOKEN","modules.combatWsBridge.apiToken":"BZSS_COMBAT_WS_TOKEN","auth.bootstrapAdminPassword":"BZSS_BOOTSTRAP_ADMIN_PASSWORD"});

export class ConfigManager {
  constructor(configPath,{legacyPath="./config.json",logger=null}={}) { this.configPath=path.resolve(process.cwd(),configPath); this.legacyPath=path.resolve(process.cwd(),legacyPath); this.logger=logger; this.config={}; this.configFiles=new Map(); this.dirtyFiles=new Set(); this.mode="unknown"; this.writeQueue=Promise.resolve(); }
  async load() { const stat=await tryStat(this.configPath); if(stat?.isDirectory()) return this.loadDirectory(); if(stat?.isFile()) return this.loadFile(this.configPath,"single-file"); const legacy=await tryStat(this.legacyPath); if(legacy?.isFile()) { this.logger?.warn?.(`LegacyConfig: using ${this.legacyPath}; run npm run config:migrate to split it.`); return this.loadFile(this.legacyPath,"legacy"); } throw error(500,"ConfigNotFound",`Configuration directory not found: ${this.configPath}`); }
  async loadDirectory() { const entries=(await fs.readdir(this.configPath,{withFileTypes:true})).filter(x=>x.isFile()&&x.name.endsWith(".json")).sort((a,b)=>a.name.localeCompare(b.name)); if(!entries.length) throw error(500,"ConfigDirectoryEmpty",`No JSON files in ${this.configPath}`); const seen=new Map(); this.config={}; this.configFiles.clear(); for(const entry of entries) { const file=path.join(this.configPath,entry.name), parsed=await readJson(file); if(!plain(parsed)) throw error(500,"InvalidConfigRoot",`${entry.name} must contain a JSON object.`); for(const [namespace,value] of Object.entries(parsed)) { if(!plain(value)) throw error(500,"InvalidConfigNamespace",`${entry.name}:${namespace} must be an object.`); if(seen.has(namespace)) throw error(500,"ConfigNamespaceConflict",`ConfigNamespaceConflict\nnamespace: ${namespace}\ndefined in:\n- ${seen.get(namespace)}\n- ${entry.name}`); if(!CONFIG_NAMESPACE_OWNERSHIP[namespace]) throw error(500,"ConfigOwnershipMissing",`No ownership configured for namespace: ${namespace}`); if(CONFIG_NAMESPACE_OWNERSHIP[namespace]!==entry.name) throw error(500,"ConfigOwnershipMismatch",`${namespace} must be defined in ${CONFIG_NAMESPACE_OWNERSHIP[namespace]}, not ${entry.name}`); rejectDiskSecrets(value,namespace,entry.name); seen.set(namespace,entry.name); this.config[namespace]=value; this.configFiles.set(namespace,file); } } this.mode="directory"; applyEnv(this.config); }
  async loadFile(file,mode) { this.config=await readJson(file); if(!plain(this.config)) throw error(500,"InvalidConfigRoot","config root must be a JSON object."); this.configFiles.clear(); Object.keys(this.config).forEach(key=>this.configFiles.set(key,file)); this.mode=mode; applyEnv(this.config); }
  get(pathText,defaultValue=undefined) { if(!pathText) return this.config; let current=this.config; for(const key of String(pathText).split(".")) { if(current==null||typeof current!=="object"||!(key in current)) return defaultValue; current=current[key]; } return current; }
  set(pathText,value) { const normalized=validPath(pathText), [root,...parts]=normalized.split("."); sensitive(normalized); if(!parts.length) throw error(400,"InvalidPath","A namespace cannot be replaced directly."); if(!this.configFiles.has(root)) { if(this.mode==="directory") throw error(400,"ConfigNamespaceMissing",`Namespace is not loaded: ${root}`); this.configFiles.set(root,this.configPath); } if(!plain(this.config[root])) this.config[root]={}; let current=this.config[root]; for(const key of parts.slice(0,-1)) { if(!plain(current[key])) current[key]={}; current=current[key]; } current[parts.at(-1)]=value; this.dirtyFiles.add(this.configFiles.get(root)); return value; }
  async save(options={}) { return this.queue(()=>this.performSave(options)); }
  async performSave({createBackup=true}={}) { const files=this.mode==="directory"?[...this.dirtyFiles]:[this.configPath], results=[]; for(const file of files) { const roots=this.mode==="directory"?[...this.configFiles].filter(([,source])=>source===file).map(([root])=>root):Object.keys(this.config); results.push(await writeJson(file,Object.fromEntries(roots.map(root=>[root,this.config[root]])),createBackup)); } this.dirtyFiles.clear(); return {ok:true,mode:this.mode,files:results,configPath:this.configPath,backupPath:results.length===1?results[0].backupPath:null}; }
  getExposedSettings() { const editor=this.get("settingsEditor",{})??{}, definitions=Array.isArray(editor.exposed)?editor.exposed:[]; return {enabled:Boolean(editor.enabled),settings:definitions.map(normalizeDef).filter(x=>x&&!secretPath(x.path)&&this.get(x.path)!==undefined).map(x=>({...x,value:clone(this.get(x.path))}))}; }
  async updateExposedSettings(changes) { return this.queue(()=>this.update(changes)); }
  async update(changes) { const editor=this.get("settingsEditor",{})??{}; if(!editor.enabled) throw error(403,"SettingsEditorDisabled","Settings editor is disabled."); if(!plain(changes)) throw error(400,"InvalidChanges","Changes must be an object map."); const defs=new Map((Array.isArray(editor.exposed)?editor.exposed:[]).map(normalizeDef).filter(Boolean).filter(x=>!secretPath(x.path)).map(x=>[x.path,x])); const pending=[]; let restartRequired=false; for(const [input,raw] of Object.entries(changes)) { const key=validPath(input), def=defs.get(key); sensitive(key); if(!def) throw error(403,"SettingNotExposed",`Setting is not exposed: ${key}`); pending.push([key,normalValue(def,raw)]); restartRequired ||= def.restartRequired; } if(!pending.length) return {...this.getExposedSettings(),restartRequired:false}; const previous=clone(this.config),dirty=new Set(this.dirtyFiles); for(const [key,value] of pending)this.set(key,value); try{await this.performSave();}catch(cause){this.config=previous;this.dirtyFiles=dirty;throw cause;} return {...this.getExposedSettings(),restartRequired}; }
  queue(task) { const run=this.writeQueue.then(task); this.writeQueue=run.then(()=>undefined,()=>undefined); return run; }
}

export async function migrateLegacyConfig({sourcePath="./config.json",targetDirectory="./config/panel",overwrite=false}={}) { const source=path.resolve(process.cwd(),sourcePath),target=path.resolve(process.cwd(),targetDirectory),config=await readJson(source); if(!plain(config))throw error(500,"InvalidConfigRoot","Legacy config root must be an object."); await fs.mkdir(target,{recursive:true}); const groups=new Map(); for(const [root,value] of Object.entries(config)){const name=CONFIG_NAMESPACE_OWNERSHIP[root];if(!name)throw error(500,"ConfigOwnershipMissing",`No ownership configured for namespace: ${root}`);if(!plain(value))throw error(500,"InvalidConfigNamespace",`Legacy namespace must be an object: ${root}`);if(!groups.has(name))groups.set(name,{});groups.get(name)[root]=stripSecrets(clone(value),root);} const files=[]; for(const [name,value]of groups){const output=path.join(target,name);if(!overwrite&&await exists(output))throw error(409,"ConfigTargetExists",`Target already exists: ${output}`);await writeJson(output,value,false);files.push(output);} return {ok:true,sourcePath:source,targetDirectory:target,files}; }

async function readJson(file){try{return JSON.parse((await fs.readFile(file,"utf8")).replace(/^\uFEFF/,""));}catch(cause){throw error(500,"ConfigParseError",`Failed to parse ${file}: ${cause.message}`);}}
async function writeJson(file,value,backup){const dir=path.dirname(file),temp=path.join(dir,`${path.basename(file)}.${process.pid}.${Date.now()}.tmp`),bak=`${file}.bak`;let copied=false;await fs.mkdir(dir,{recursive:true});try{await fs.writeFile(temp,`${JSON.stringify(value,null,2)}\n`,"utf8");if(backup&&await exists(file)){await fs.copyFile(file,bak);copied=true;}try{await fs.rename(temp,file);}catch(cause){if(!copied)throw cause;try{await fs.rm(file,{force:true});await fs.rename(temp,file);}catch(replace){await fs.copyFile(bak,file);throw replace;}}return {configPath:file,backupPath:copied?bak:null};}finally{await fs.rm(temp,{force:true}).catch(()=>{});}}
async function tryStat(file){try{return await fs.stat(file);}catch(cause){if(cause?.code==="ENOENT")return null;throw cause;}} async function exists(file){return fs.access(file).then(()=>true,()=>false);}
function applyEnv(config){for(const[key,env]of Object.entries(SECRETS)){const value=process.env[env];if(typeof value==="string"&&value.trim())put(config,key,value.trim());}}
function rejectDiskSecrets(value,root,file){for(const[key,env]of Object.entries(SECRETS)){if(key==="rcon.password")continue;const diskValue=key.startsWith(`${root}.`)?read(value,key.slice(root.length+1)):undefined;if(diskValue!==undefined&&String(diskValue??"").trim())throw error(500,"ConfigSecretOnDisk",`${file} must not contain ${key}; use ${env}.`);}}
function stripSecrets(value,root){for(const key of Object.keys(SECRETS))if(key.startsWith(`${root}.`))drop(value,key.slice(root.length+1));return value;}
function read(value,key){return key.split(".").reduce((current,part)=>current&&typeof current==="object"?current[part]:undefined,value);} function put(value,key,replacement){const parts=key.split(".");let current=value;for(const part of parts.slice(0,-1)){if(!plain(current[part]))current[part]={};current=current[part];}current[parts.at(-1)]=replacement;} function drop(value,key){const parts=key.split(".");let current=value;for(const part of parts.slice(0,-1)){if(!plain(current?.[part]))return;current=current[part];}delete current?.[parts.at(-1)];}
function plain(value){return Boolean(value)&&typeof value==="object"&&!Array.isArray(value);} function validPath(value){const normalized=String(value??"").trim();if(!normalized)throw error(400,"InvalidPath","Path must be a non-empty string.");return normalized;} function secretPath(value){const key=String(value??"").toLowerCase();return key==="auth.users"||key.startsWith("auth.users.")||key==="database.dir"||key==="database.filename"||key.split(".").some(x=>/password|secret|token|key/i.test(x));} function sensitive(key){if(secretPath(key))throw error(403,"SensitiveSettingBlocked",`Sensitive setting path is blocked: ${key}`);}
function normalizeDef(raw){if(!plain(raw))return null;const path=String(raw.path??"").trim(),type=String(raw.type??"").trim().toLowerCase();if(!path||!["boolean","number","string","select"].includes(type))return null;const result={path,label:String(raw.label??path).trim()||path,type,description:String(raw.description??"").trim(),restartRequired:Boolean(raw.restartRequired),advanced:Boolean(raw.advanced)};if(type==="number"){const min=Number(raw.min),max=Number(raw.max);if(Number.isFinite(min))result.min=min;if(Number.isFinite(max))result.max=max;}if(type==="select"){result.options=Array.isArray(raw.options)?raw.options.map(x=>{const value=plain(x)?x.value??x.key??x.id:x;return value==null?null:{label:String(plain(x)?x.label??value:value),value};}).filter(Boolean):[];if(!result.options.length)return null;}return result;}
function normalValue(def,value){if(value===undefined)throw error(400,"InvalidSettingValue",`Missing value for ${def.path}`);if(def.type==="boolean"){if(typeof value==="boolean")return value;if(value===0||value==="0"||String(value).toLowerCase()==="false")return false;if(value===1||value==="1"||String(value).toLowerCase()==="true")return true;throw error(400,"InvalidSettingValue",`Invalid boolean value for ${def.path}`);}if(def.type==="number"){const n=Number(value);if(!Number.isFinite(n))throw error(400,"InvalidSettingValue",`Invalid number value for ${def.path}`);if(Number.isFinite(def.min)&&n<def.min)throw error(400,"SettingBelowMin",`${def.path} must be at least ${def.min}`);if(Number.isFinite(def.max)&&n>def.max)throw error(400,"SettingAboveMax",`${def.path} must be at most ${def.max}`);return n;}if(def.type==="string"){if(value==null)throw error(400,"InvalidSettingValue",`Invalid string value for ${def.path}`);return String(value);}const found=def.options.find(x=>x.value===value||String(x.value)===String(value));if(!found)throw error(400,"InvalidSettingValue",`Invalid select value for ${def.path}`);return found.value;}
function clone(value){if(value==null||typeof value!=="object")return value;try{return structuredClone(value);}catch{return JSON.parse(JSON.stringify(value));}} function error(statusCode,code,message){const value=new Error(message);value.statusCode=statusCode;value.code=code;return value;}
